pylint:
  disable:
    - bare-except
    - unused-argument
    - pointless-string-statement
    - too-many-locals
    - too-many-arguments
    - protected-access
    - unused-variable
    - super-on-old-class

pep8:
  disable:
    - E1002

requirements:
    - requirements.txt
